/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    VInput: typeof import('./src/shared/ui/vInput/VInput.vue')['default']
    VSvg: typeof import('./src/shared/ui/VSvg/VSvg.vue')['default']
    VTabs: typeof import('./src/shared/ui/VTabs/VTabs.vue')['default']
  }
}
